<%@ Page Title="Initial Page" Language="C#" MasterPageFile="~/master.Master" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="VEFVerkefni.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contentHolder" runat="server">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate ligula vitae est iaculis pretium. Sed dolor dolor, interdum in augue eu, dictum sodales turpis. Nunc sapien nisi, ornare vitae massa vitae, porttitor ultrices ipsum. Pellentesque sapien mi, consectetur non accumsan quis, iaculis scelerisque ligula. Donec bibendum in quam eu blandit. Aenean dictum risus vitae ligula pharetra, in tempor tellus interdum. Fusce fermentum ligula vel urna eleifend aliquet. Praesent a elit ultrices, rhoncus augue vel, gravida nulla. Nulla at consequat risus.</p>

    <p>Morbi ullamcorper tempus tortor, quis volutpat tellus sodales ut. Donec luctus turpis quis sem placerat, et ullamcorper lacus dapibus. Pellentesque eu metus vestibulum, congue enim non, tempus nibh. Donec pretium lorem nec felis ultrices tincidunt. Sed dictum quam sapien, at venenatis felis luctus id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc et turpis rhoncus, mattis nisi a, vestibulum erat. Suspendisse in fringilla urna. Sed dapibus varius risus varius sodales. Nulla justo turpis, maximus nec mi et, ultricies cursus quam.</p>

    <p>Morbi porttitor, quam sit amet facilisis eleifend, dui odio tempor libero, ut cursus leo orci eu ante. Etiam id ornare quam. Nullam dictum ornare fermentum. Phasellus eget dui libero. Nullam molestie dui tortor, id consequat sem sodales non. Curabitur ac tincidunt risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum id tempus lorem. Proin tristique porttitor sapien blandit porta. Cras nec velit dolor. Ut nisl massa, pretium eu nisl id, vulputate luctus lectus. Vivamus mi arcu, finibus sed nibh eget, mollis consectetur ante. Aenean aliquam pellentesque auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum ornare blandit. Nulla euismod dignissim luctus.</p>

    <p>Praesent sodales nulla ligula, eget hendrerit ante efficitur et. Donec in ullamcorper arcu. Nullam ut rutrum nunc. Mauris auctor tellus rhoncus sem bibendum, ac euismod dolor blandit. Vestibulum convallis mi at viverra porta. Vestibulum lacus purus, sagittis sit amet elit vitae, lacinia consectetur leo. Fusce velit augue, ultrices viverra tristique in, imperdiet vitae diam. Morbi ultricies lacinia venenatis. Morbi malesuada magna vitae venenatis aliquet. Etiam cursus convallis nisi non vulputate.</p>

    <p>Morbi ut suscipit neque. Nulla facilisi. Curabitur fringilla eros interdum, imperdiet odio at, laoreet purus. Fusce consectetur dictum eros sit amet auctor. Etiam sapien ex, semper a purus eu, eleifend blandit lectus. Sed ante arcu, accumsan dapibus ornare in, rhoncus in urna. Pellentesque ac turpis at diam dignissim ornare at aliquet tortor. Donec nibh lectus, pharetra id accumsan in, tincidunt non mauris.</p>
</asp:Content>